### ISSUE TITLE
Issues with Economy

### ISSUE THREAD

**Issue by iiEpixx** [Ktar5/Info-Board#127]
Hi, I'm using InfoBoard for the first time and I'm having some problems.

The plugin is working fine and looks very nice, that is until I try displaying player balance.
I'm using MineConomy with Vault (yes, I have tried other economy plugins as well) and every time I try to display the player's balance with %vault_eco_balance% the InfoBoard simply dissappears.

Here's what my board.yml looks like:
InfoBoard:
```
  '1':
    ShowTime: 20
    global:
      default:
        Title: '&B&lThe Enchanted Forest'
        Rows:
        - '&6----[InfoBoard]----'
        - ' '
        - '&e&lWelcome!'
        - '&l%player_name%'
        - ' '
        - '&a&lHealth:'
        - '&e%player_health%&a/&c%player_max_health%'
        - ' '
        - '&2&lBalance:'
        - '%vault_eco_balance%'
        - ' '
        - '&e&lWebsite:'
        - '<website>'
        - '&6----[InfoBoard]----'
  '2':
    ShowTime: 10
    global:
      default:
        Title: '&e&lPlayer Stats'
        Rows:
        - '&6----[InfoBoard]----'
        - ' '
        - '&e&lDate Joined:'
        - '&l%player_first_join_date%'
        - ' '
        - '&a&lWorld:'
        - '&e%player_world%'
        - ' '
        - '&5&lLocation:'
        - '&a%player_x%&7, &a%player_y%&7, &a%player_z%'
        - ' '
        - '&e&lWebsite:'
        - '<website>'
        - '&6----[InfoBoard]----'
      Admin:
        Title: '&e&lServer Stats'
        Rows:
        - '&6----[InfoBoard]----'
        - ' '
        - '&a&lMemory:'
        - '&e%server_ram_used%&7/&e%server_ram_max%'
        - ' '
        - '&d&lUptime'
        - '&f%server_uptime%'
        - ' '
        - '&6----[InfoBoard]----'
```

I'm not quite sure what the problem is, as I've tried redownloading PAPI and I have all the correct extensions downloaded.
Help is greatly appreciated.

Thanks!
