### ISSUE TITLE
Incorrect prefix shown with placeholder %luckperms_prefix%

### ISSUE THREAD

**Issue by spencermacca** [Ktar5/Info-Board#156]
Hi! Not sure who's fault this is, whether its PAPI, this plugin, or LuckPerms but I decided to post here as it's the only plugin that fails to show the correct prefix. Basically, I'm in the group "owner" and the prefix is "&4Owner" with LuckPerms. However, instead, Infoboard shows a completely different group prefix (Ultra) that I do not have in my parent groups or any relation to. I have tried logging on with a completely different Minecraft account that was assigned to a completely different group to see if it was a problem with my permissions, but the exact same thing came up. 

My board YML looks like the following
```
InfoBoard:
  '1':
    ShowTime: 1000
    global:
      default:
        Title: '&b&lCloudCraft &7| &rSkyblock'
        Rows:
        - '&7&m-----------------'
        - '&b&lYou'
        - ' &3* &rRank: %luckperms_prefix%'
        - ' &3* &rMoney: &a$%vault_eco_balance_formatted%'
        - ' '
        - '&b&lIsland'
        - ' &3* &rLevel: &b%askyblock_level%'
        - ' &3* &rMembers: &b%askyblock_team_size% '
        - '&7&l&m----------------'
```
