### ISSUE TITLE
Unable to add lines to my scoreboard

### ISSUE THREAD

**Issue by spencermacca** [Ktar5/Info-Board#159]
For the first and last row of my scoreboard, I have lines inputted
`- '&7&l&m----------'`
However, if both the top and bottom row are the same with the lines as shown above, the top row will disappear.

**My board.yml**
```
InfoBoard:
  '1':
    ShowTime: 99999999999999999999999999999999
    global:
      default:
        Title: '&c&lSky&r&4End'
        Rows:
        - '&7&l&m----------'
        - '&4&lYou'
        - '&cRank: &fPlaceholder'
        - '&cBal: &f$0'
        - ' '
        - '&4&lYour Island'
        - '&cLevel: &f0'
        - '&cMembers: &f1'
        - '&7&l&m----------'
```
